create table cost_center (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null,
    deleted boolean not null,
    primary key (id)
);

create table cost_center_address (
    cost_center_id int not null,
    address varchar(255) not null,
    address_order int not null
);
alter table cost_center_address add constraint FK81ch991kndi287373423ddgle2u foreign key (cost_center_id) references cost_center;

create table cost_center_projects (
    cost_center_id int not null,
    project_key varchar(255) not null
);
alter table cost_center_projects add constraint FK81ch991kndi28737322632gle2u foreign key (cost_center_id) references cost_center;
alter table cost_center_projects add constraint FK8173h32kndi28737322632gle2u foreign key (project_key) references project;

create table billing_period (
    id bigint generated by default as identity,
    start Date not null,
    due_date Date not null,
    created_date varchar(255) not null,
    primary key (id)
);

create table bill (
    id bigint generated by default as identity,
    cost_center_id int not null,
    billing_period_id int not null,
    primary key (id)
);
alter table bill add constraint FKtddtns6av4ubcsn0cor734012 foreign key (cost_center_id) references cost_center;
alter table bill add constraint FKtddtns6av4ub3313cor734012 foreign key (billing_period_id) references billing_period;

create table project_bill (
    id bigint generated by default as identity,
    project_key varchar(255) not null,
    amount decimal not null,
    total_non_deleted_tasks int not null,
    created_tasks int not null,
    bill_id int not null,
    primary key (id)
);
alter table project_bill add constraint FKdqrjtquw273641grps5dk7c0w foreign key (project_key) references project;
alter table project_bill add constraint FK634739nv941a25yf8fepgkein foreign key (bill_id) references bill;
